/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with username or email */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and revoke refresh token */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Create user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier (UUID) */
                userId: string;
            };
            cookie?: never;
        };
        /** Get user by id */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        /** Delete user */
        delete: operations["deleteUserById"];
        options?: never;
        head?: never;
        /** Update user */
        patch: operations["updateUserById"];
        trace?: never;
    };
    "/users/{username}": {
        parameters: {
            query?: {
                /** @description Pretty print response */
                pretty_print?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by user name
         * @description Some description of the operation.
         *     You can use `markdown` here.
         */
        get: operations["getUserByName"];
        /**
         * Updated user
         * @description This can only be done by the logged in user.
         */
        put: operations["updateUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/echo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Echo test
         * @description Receive the exact message you've sent
         */
        post: operations["echo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: email
         * @description User email address
         * @example john.smith@example.com
         */
        Email: string;
        /** @description Registration payload for creating a new account */
        AuthRegisterRequest: {
            /** @example johnsmith */
            username: string;
            email: components["schemas"]["Email"];
            /**
             * Format: password
             * @description User password
             * @example StrongPass!123
             */
            password: string;
            /** @example John */
            firstName: string;
            /** @example Smith */
            lastName: string;
        };
        /** @description Access and refresh tokens issued after authentication */
        AuthTokens: {
            /**
             * @description JWT used for authenticated requests
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description Long-lived token used to obtain a new access token
             * @example dcb29211-7b4e-4a1c-8ccf-4a4b6c8d2a51
             */
            refreshToken: string;
            /**
             * Format: int64
             * @description Access token lifetime in seconds
             * @example 3600
             */
            expiresIn: number;
            /**
             * @description Token type indicator
             * @default Bearer
             */
            tokenType: string;
        };
        /** @description Rich user profile returned by the API */
        UserProfile: {
            /**
             * Format: uuid
             * @example 8b2e7f2d-4fd5-40a0-9e65-7e3d4c9f0f11
             */
            id: string;
            /** @example johnsmith */
            username: string;
            email: components["schemas"]["Email"];
            /** @example John */
            firstName: string;
            /** @example Smith */
            lastName: string;
            /**
             * @description Role assigned to the user
             * @example user
             * @enum {string}
             */
            role: "user" | "admin";
            /**
             * @description Indicates whether the user account is active
             * @example true
             */
            isActive: boolean;
            /**
             * Format: date-time
             * @description Timestamp of the most recent successful login
             * @example 2024-05-10T14:32:10Z
             */
            lastLoginAt?: string;
            /**
             * Format: date-time
             * @example 2024-01-01T08:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-05-10T14:32:10Z
             */
            updatedAt: string;
        };
        /** @description Tokens and user profile returned after authentication */
        AuthLoginResponse: {
            tokens: components["schemas"]["AuthTokens"];
            user: components["schemas"]["UserProfile"];
        };
        /** @description Credentials used to authenticate a user */
        AuthLoginRequest: {
            /**
             * @description Username or email used to login
             * @example john.smith@example.com
             */
            usernameOrEmail: string;
            /**
             * Format: password
             * @description User password
             * @example StrongPass!123
             */
            password: string;
        };
        /** @description Payload used to obtain a new access token */
        AuthRefreshRequest: {
            /**
             * @description Valid refresh token issued during login or registration
             * @example dcb29211-7b4e-4a1c-8ccf-4a4b6c8d2a51
             */
            refreshToken: string;
        };
        /** @description Tokens returned after refreshing an access token */
        AuthRefreshResponse: {
            tokens: components["schemas"]["AuthTokens"];
        };
        /** @description Optional payload to revoke a specific refresh token during logout */
        AuthLogoutRequest: {
            /**
             * @description Refresh token to invalidate (omit to logout all sessions)
             * @example dcb29211-7b4e-4a1c-8ccf-4a4b6c8d2a51
             */
            refreshToken?: string;
        };
        /** @description Pagination metadata for list responses */
        PaginationMeta: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            pageSize: number;
            /** @example 125 */
            totalItems: number;
            /** @example 7 */
            totalPages: number;
        };
        /** @description Paginated list of users */
        UserListResponse: {
            data: components["schemas"]["UserProfile"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /** @description Payload used to create a new user by an administrator */
        UserCreateRequest: {
            /** @example johnsmith */
            username: string;
            email: components["schemas"]["Email"];
            /**
             * Format: password
             * @description Temporary or initial password
             * @example StrongPass!123
             */
            password: string;
            /** @example John */
            firstName: string;
            /** @example Smith */
            lastName: string;
            /**
             * @default user
             * @enum {string}
             */
            role: "user" | "admin";
            /** @default true */
            isActive: boolean;
        };
        /** @description Partial update payload for an existing user */
        UserUpdateRequest: {
            email?: components["schemas"]["Email"];
            /** @example John */
            firstName?: string;
            /** @example Smith */
            lastName?: string;
            /**
             * Format: password
             * @description New password; omit to keep current
             * @example StrongPass!123
             */
            password?: string;
            /** @enum {string} */
            role?: "user" | "admin";
            isActive?: boolean;
        };
        User: {
            /**
             * @description User supplied username
             * @example John78
             */
            username?: string;
            /**
             * @description User first name
             * @example John
             */
            firstName?: string;
            /**
             * @description User last name
             * @example Smith
             */
            lastName?: string;
            email?: components["schemas"]["Email"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description date in UTC when token expires */
        ExpiresAfter: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRegisterRequest"];
            };
        };
        responses: {
            /** @description User registered and authenticated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginResponse"];
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Username or email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many attempts, try later */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequest"];
            };
        };
        responses: {
            /** @description New tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRefreshResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AuthLogoutRequest"];
            };
        };
        responses: {
            /** @description Logout successful */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of records per page */
                pageSize?: number;
                /** @description Free text search by username or email */
                search?: string;
                /** @description Filter by role */
                role?: "user" | "admin";
                /** @description Filter active/inactive users */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Username or email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier (UUID) */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier (UUID) */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier (UUID) */
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserByName: {
        parameters: {
            query?: {
                /** @description Pretty print response */
                pretty_print?: boolean;
                /** @description Filter users without email */
                with_email?: boolean;
            };
            header?: never;
            path: {
                /** @description The name that needs to be fetched */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "username": "user1",
                     *       "email": "user@example.com"
                     *     }
                     */
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUser: {
        parameters: {
            query?: {
                /** @description Pretty print response */
                pretty_print?: boolean;
            };
            header?: never;
            path: {
                /** @description The name that needs to be updated */
                username: string;
            };
            cookie?: never;
        };
        /** @description Updated user object */
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/xml": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid user supplied */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    echo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Echo payload */
        requestBody: {
            content: {
                "application/json": string;
                "application/xml": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description calls per hour allowed by the user */
                    "X-Rate-Limit"?: number;
                    "X-Expires-After": components["headers"]["ExpiresAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                    "application/xml": string;
                    "text/csv": string;
                };
            };
        };
    };
}
